### ISSUE TITLE
Access denied for ' '@'localhost' Doesnt seem to have the username i added in

### ISSUE THREAD

**Issue by Thatguy553** [dvaJi/ReaderFront#662]
So ive set all the correct information in the .env in the api file, but i still get an error such as 
![image](https://user-images.githubusercontent.com/54968182/77699767-5ece4300-6f89-11ea-8130-a40d69bea0f0.png)

even though i have the username set it doesnt seem to show it 
![image](https://user-images.githubusercontent.com/54968182/77699842-81f8f280-6f89-11ea-9261-88b109f9a89b.png)
And the keys that are in their are just temporary doesnt matter if others see them

**Comment by Thatguy553** [comment]
This is when i run setup:db

**Comment by Thatguy553** [comment]
This is when i run setup:db

![image](https://user-images.githubusercontent.com/54968182/77700102-eb790100-6f89-11ea-9279-5056ab150852.png)
![image](https://user-images.githubusercontent.com/54968182/77700139-fcc20d80-6f89-11ea-9100-6e33767d3968.png)

**Comment by dvaJi** [comment]
This is a bug, it seems that the sequelize script is not loading the configuration from the `.env` file.

**Comment by Thatguy553** [comment]
Ah alright, any ETA on a fix? Or any quick fix I can do?

**Comment by dvaJi** [comment]
@Thatguy553 It is not a critical bug, so is not necessary to put an ETA. And I think the bug is in the `.sequelizerc` file, so you might take a look at it and check why the env variables are not being loaded.

**Comment by Thatguy553** [comment]
Ah, I haven't been able to get it setup, when I go to do setup:db etc I get
access denied even though I've added the correct password and database
name, so I assumed because the username isn't loading it wasn't allowing me
to to it

**Comment by Thatguy553** [comment]
also, this could be an issue for me because im not familiar with mariadb, i followed the steps and installed mariadb but once i opened the client and selected my database n such, the npm commands got syntax errors, and when i ran the commands in the directory through a normal command prompt the command ran but resulted in the pics above, at first it would tell me no database selected, have no idea how to select the database

**Comment by dvaJi** [comment]
@Thatguy553 I updated the `.sequelizerc` to load the .env file, could you try now?
And regarding mariadb, it's just exactly the same as MySQL.

**Comment by Thatguy553** [comment]
Yea just a minute I'll load it up now

**Comment by Thatguy553** [comment]
alright so its different now, migrate:db seems to work except for whatever this is, doesnt seem to be a fatal error though?
![image](https://user-images.githubusercontent.com/54968182/77981566-4e470100-72d8-11ea-8211-a5f252c9a70b.png)

but once i do db:seed it works fine up until here:
![image](https://user-images.githubusercontent.com/54968182/77981634-82222680-72d8-11ea-9108-3d8aa450a53e.png)

am i doing something wrong? i did a fresh install of all the files, but i did fill out the .env.example in the root and api folder and renamed them to .env, i did this assuming they needed to be filled out because without doing so it would usually tell me no database selected

**Comment by dvaJi** [comment]
I updated the code and tested creating a new database, now it should work.

**Comment by Thatguy553** [comment]
Alright, I'll try it once I get home, thanks

**Comment by Thatguy553** [comment]
so now it seems to have all worked. Thanks! one thing though, did i miss something on creating an admin account or is this another bug? When i run the dev:admin command it starts it up and brings me to a page with the option of logging in or to sign up, but in sign up no matter what it tells me there was an error signing up and i did try changing the password for the admin account in the database to test it that way but it just tells me incorrect credentials. Did i miss something?

![image](https://user-images.githubusercontent.com/54968182/78197959-00a3d300-7455-11ea-8a81-9566ea6bf47d.png)

it doesnt give any errors

**Comment by Thatguy553** [comment]
I actually just checked the chrome console and seen this

![image](https://user-images.githubusercontent.com/54968182/78198096-8162cf00-7455-11ea-9f3a-e258782e7b54.png)

**Comment by dvaJi** [comment]
The error net::ERR_CONNECTION_REFUSED means that you, either didn´t start the API or you got some errors.
Did you run `npm run dev:api`?

**Comment by Thatguy553** [comment]
I did, but i got these errors then and now.

![image](https://user-images.githubusercontent.com/54968182/78208956-b847dd80-7473-11ea-8048-234370725af8.png)

**Comment by dvaJi** [comment]
ugh, the script was missing :(, I write it in the README file but not implemented in the package.json lol.
Now it should work.

**Comment by Thatguy553** [comment]
Lmao, alright I'll try it again when I get on my pc

**Comment by Thatguy553** [comment]
so far so good, though it does seem the some of the dependencies installed are the wrong versions.

![image](https://user-images.githubusercontent.com/54968182/78510818-00158000-7766-11ea-90d6-68af78fe4b2f.png)

![image](https://user-images.githubusercontent.com/54968182/78510832-21766c00-7766-11ea-94e6-7476758cf75b.png)

Once i created an account it told me there was an error but i received an email to verify my account, so i did that and it brought me here

![image](https://user-images.githubusercontent.com/54968182/78510981-14a64800-7767-11ea-873f-7a81137661c7.png)


If you need the rest of the page let me know and ill get all of it

**Comment by Thatguy553** [comment]
![image](https://user-images.githubusercontent.com/54968182/78511042-95fdda80-7767-11ea-9fa0-fabdefb79249.png)

![image](https://user-images.githubusercontent.com/54968182/78511049-a1510600-7767-11ea-8a60-84d5b56a178d.png)

![image](https://user-images.githubusercontent.com/54968182/78511060-b463d600-7767-11ea-9b4a-3d87b2371b05.png)

**Comment by dvaJi** [comment]
I could not reproduce the error with `babel-jest` and `jest`.
and I fixed the error in the Activate component, it was related to an [async function in useEffect](https://github.com/facebook/react/issues/14326)

**Comment by Thatguy553** [comment]
Alright I'll try again tomorrow thanks for the help!

**Comment by Thatguy553** [comment]
Doesnt post any errors in logs or anything but still tells me there was an issue creating your account no matter what i do.

the first account i created was with the email i used in the .env files to set up, but it didnt send me an email like before, so i tried creating an account with another email.

then it sent me an email to verify my account but once i logged in it told me unauthorized.

Then i went into the database, apparently the first email is verified but the password doesnt work.

 So then i stole that accounts activation token and added it to the second account i created. It then let me in, so it seems to work as long as you go through those extra steps lol, whatever the issue is with creating an account makes it a pain in the arse

**Comment by dvaJi** [comment]
Its because the account needs to have the `ADMIN` role, right now it has to be modified directly in the database (check the `user` model https://github.com/dvaJi/ReaderFront/blob/master/api/src/modules/user/model.js#L17).
I will work like that until I or someone else works on #437, and I think I have to create a new issue to handle the initial setup.

**Comment by Thatguy553** [comment]
Alright thanks for the info
