### ISSUE TITLE
[Feature Request] Add screenshots and/or demo site

### ISSUE THREAD

**Issue by whalehub** [dvaJi/ReaderFront#864]
It would be cool to see what this CMS looks like without having to install it first.

**Comment by whalehub** [comment]
The following site seems to be using this CMS, so I'm closing this issue: https://knightnoscanlation.com/

**Comment by jhin1m** [comment]
This site using Wordpress and Madara theme.

> https://knightnoscanlation.com/

**Comment by whalehub** [comment]
@jhin1m Thanks for the info. Do you know of a website which is using ReaderFront?

**Comment by dvaJi** [comment]
@whalehub I'm sorry for the late response, but https://ravens-scans.com/ is using ReaderFront.

**Comment by whalehub** [comment]
@dvaJi Thanks!
